- hosts: 'server'
  become: true
  gather_facts: false
  tasks:
    - name: 'Download zabbix_package'
      uri:
        url: 'https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-3+bionic_all.deb'
        dest: '/tmp/zabbix_package.deb'
      notify: "download_again"
        
    - name: 'Installing zabbix_package'
      apt:
        deb: '/tmp/zabbix_package.deb'
        update_cache: true
        state: "present"

    - name: 'Install Zabbix server'
      apt:
        name: 'zabbix-server-mysql'
        state: 'present'
  handlers: 
    - name: "download_again"
      debug:
        msg: "You are again downloading the same package, try to reconfigure and exclude downloading if the needful package already exist"
