- hosts: 'monitoring'
  become: true
  gather_facts: false
  tasks:
    - name: 'Download zabbix_package'
      uri:
        url: 'https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-3+bionic_all.deb'
        dest: '/tmp/zabbix_package.deb'
         
    - name: 'Installing zabbix_package'
      apt: 
        deb: '/tmp/zabbix_package.deb'
        update_cache: true
        state: "present"
   
   - name: 'Installing Zabbix_agent'
      apt:
        name: 'zabbix-agent'
        state: 'present'
